### ISSUE TITLE
Token is persisted in state storage backend

### ISSUE THREAD

**Issue by nicktrav** [pulumi/pulumi-github#95]
I have a use case for programatically setting the GitHub token in a new instance of a provider, as follows:

```go
provider, err := github.NewProvider(ctx, conf.Organization, &github.ProviderArgs{
	Organization: pulumi.String(conf.Organization),
	Token:        pulumi.String(token),
})
```

Specifically, catering for multiple users, each with their own token, with varying degrees of permissions associated with them.

I noticed that changing the token results in a diff in the state. I looked in my state file (I'm persisting in a private S3 bucket) and I noticed that the token ends up in there, in plaintext.

The behavior seems to be the same if I set the token using the `GITHUB_TOKEN` environment variable, as mentioned in the docs.

The only way I can find that _avoids_ putting the token in the state file is if I encrypt it in the Pulumi config. However, this doesn't work well when we have multiple users, each with their own token.

Is there that I can set a token programatically, _and_ ensure that it is not persisted in the state backend?

**Comment by stack72** [comment]
Hi @nicktrav 

I'm sorry this is the case here - please can you tell me what version of pulumi-github you are using? I'd like to be able to get to the bottom of this?

Thanks

Paul

**Comment by nicktrav** [comment]
Hey @stack72 - thanks for looking. I'm using the following:

```
github.com/pulumi/pulumi-github/sdk v1.5.0
```

I used the vanilla `go get` instructions from the README.

**Comment by stack72** [comment]
Hi @nicktrav 

Ok, that's completely my fault here - please can you try the newest package as follows:

```
github.com/pulumi/pulumi-github/sdk/v2 v2.5.1
```

I am pretty sure the new packages do not have this issue - I will update the README for that (sorry!!)

P.

**Comment by nicktrav** [comment]
I was able to get what I needed by referencing the `v3` packages. It's slightly confusing though, given the latest tagged version in the repo is version 2.x.

I did some digging in the Git history, and it looks like the version in the module file changed between versions `2.2.0` and `2.3.0`:

https://github.com/pulumi/pulumi-github/blob/v2.2.0/sdk/go.mod
https://github.com/pulumi/pulumi-github/blob/v2.3.0/sdk/go.mod

However, even though I'm now using the latest version of the library (version 252c5ee178bb516332079422b81fc8d5917c615b), I still see the token being persisted in the state file, and changes to the token are still shown in the diff - both when using `GITHUB_TOKEN` as well as when setting it programatically when setting up the provider.

**Comment by stack72** [comment]
Ok that’s a breakage in versioning and I will rectify that first thing
tomorrow

I’m going to test the secrets thing as well - we may well have a weird bug
here

Stick with me until tomorrow until I can fix this

P.

**Comment by stack72** [comment]
Hey @nicktrav 

I am just about to cut v3.0.0 of this package and as you can see from my state file, no secret information is contained 👍

```
{
                "urn": "urn:pulumi:dev::github-go::pulumi:providers:github::test",
                "custom": true,
                "id": "1e9b5306-69bc-45fc-becd-eb1b7ee7b900",
                "type": "pulumi:providers:github",
                "inputs": {
                    "baseUrl": "https://api.github.com/",
                    "organization": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "AAABABGM6BrL6QJjR0B2aYyq13AcVWzPkmFNKDVeiM9Djdox0nX/Ig0oII9Rzq3QDhkJE4K8dnef2A=="
                    },
                    "token": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "AAABAGG2bBO17yDx1EJtRX1rGYkqoXLCLa3VZC50ACXpGOa5Vgkm90Rk/6dbEVmIwTUCy8m3qt1t55D+gWkBww1Bqq2erzf9B3g="
                    }
                },
                "outputs": {
                    "baseUrl": "https://api.github.com/",
                    "organization": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "AAABABGM6BrL6QJjR0B2aYyq13AcVWzPkmFNKDVeiM9Djdox0nX/Ig0oII9Rzq3QDhkJE4K8dnef2A=="
                    },
                    "token": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "AAABAGG2bBO17yDx1EJtRX1rGYkqoXLCLa3VZC50ACXpGOa5Vgkm90Rk/6dbEVmIwTUCy8m3qt1t55D+gWkBww1Bqq2erzf9B3g="
                    }
                },
                "parent": "urn:pulumi:dev::github-go::pulumi:pulumi:Stack::github-go-dev",
                "propertyDependencies": {
                    "baseUrl": [],
                    "organization": [],
                    "token": []
                }
            },
```

This should solve this issue

Paul

**Comment by stack72** [comment]
Closed via v3.0.0 release

**Comment by nicktrav** [comment]
Hey @stack72 - thanks for your work on this!

I've upgraded to `v3.0.0` no dramas. Unfortunately, I'm still seeing the token being persisted in the state file.

Here's some combinations that I've tried.

Removed setting the token in the provider:

```diff
diff --git a/github/main.go b/github/main.go
index 0f25b33..3dc6043 100644
--- a/github/main.go
+++ b/github/main.go
@@ -17,14 +16,13 @@ func main() {
                        return err
                }

                provider, err := github.NewProvider(ctx, conf.OrgConfig.Name, &github.ProviderArgs{
                        Organization: pulumi.String(conf.OrgConfig.Name),
-                       Token:        pulumi.String(token),
                })

                err = org.CreateOrgMembers(ctx, provider, conf.OrgConfig)
```

This indeed does unset the token in the state file. Though I'm left with it set as an empty string:

```json
                {
                    "urn": "urn:pulumi:prod::github::pulumi:providers:github::snipped",
                    "custom": true,
                    "id": "60255ba8-f34f-45f3-971e-2110d548992f",
                    "type": "pulumi:providers:github",
                    "inputs": {
                        "baseUrl": "https://api.github.com/",
                        "organization": "snipped",
                        "token": ""
                    },
                    "outputs": {
                        "baseUrl": "https://api.github.com/",
                        "organization": "snipped",
                        "token": ""
                    },
                    "parent": "urn:pulumi:prod::github::pulumi:pulumi:Stack::github-prod",
                    "propertyDependencies": {
                        "baseUrl": [],
                        "organization": [],
                        "token": []
                    }
                },
```

If I now try and set my credentials via exporting the `GITHUB_TOKEN` environment variable, the diff shows it wanting to write the token back to the state file:

```console
$ export GITHUB_TOKEN=$(cat ~/.config/github/token)
$ pulumi preview --diff
Previewing update (prod):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:prod::github::pulumi:pulumi:Stack::github-prod]
    ~ pulumi:providers:github: (update)
        [id=60255ba8-f34f-45f3-971e-2110d548992f]
        [urn=urn:pulumi:prod::github::pulumi:providers:github::snipped]
        baseUrl     : "https://api.github.com/"
        organization: "snipped"
      + token       : "REDACTED"
Resources:
    ~ 1 to update
    74 unchanged
```

I've also tried manually editing the state file to remove the `token` key from the `inputs` and `ouputs`, but to no avail.

Here are the versions I'm now running:

```diff
diff --git a/github/go.mod b/github/go.mod
index df3d049..46a38a9 100644
--- a/github/go.mod
+++ b/github/go.mod
@@ -4,8 +4,8 @@ go 1.15

 require (
        github.com/mitchellh/go-homedir v1.1.0
-       github.com/pulumi/pulumi-github/sdk/v3 v3.0.0-20210128173839-252c5ee178bb
-       github.com/pulumi/pulumi/sdk/v2 v2.18.0
+       github.com/pulumi/pulumi-github/sdk/v3 v3.0.0
+       github.com/pulumi/pulumi/sdk/v2 v2.19.0
        gopkg.in/yaml.v2 v2.2.8
 )
```

```console
$ pulumi version
v2.19.0
```

**Comment by nicktrav** [comment]
I managed to get this working with the following local modifications to the `github-sdk`:

```diff
diff --git a/sdk/go/github/provider.go b/sdk/go/github/provider.go
index 1726149..5d9cdb0 100644
--- a/sdk/go/github/provider.go
+++ b/sdk/go/github/provider.go
@@ -31,9 +31,6 @@ func NewProvider(ctx *pulumi.Context,
 	if args.Organization == nil {
 		args.Organization = pulumi.StringPtr(getEnvOrDefault("", nil, "GITHUB_ORGANIZATION").(string))
 	}
-	if args.Token == nil {
-		args.Token = pulumi.StringPtr(getEnvOrDefault("", nil, "GITHUB_TOKEN").(string))
-	}
 	var resource Provider
 	err := ctx.RegisterResource("pulumi:providers:github", name, args, &resource, opts...)
 	if err != nil {
@@ -51,8 +48,6 @@ type providerArgs struct {
 	Organization *string `pulumi:"organization"`
 	// The GitHub owner name to manage. Use this field instead of `organization` when managing individual accounts.
 	Owner *string `pulumi:"owner"`
-	// The OAuth token used to connect to GitHub. `anonymous` mode is enabled if `token` is not configured.
-	Token *string `pulumi:"token"`
 }
 
 // The set of arguments for constructing a Provider resource.
@@ -65,8 +60,6 @@ type ProviderArgs struct {
 	Organization pulumi.StringPtrInput
 	// The GitHub owner name to manage. Use this field instead of `organization` when managing individual accounts.
 	Owner pulumi.StringPtrInput
-	// The OAuth token used to connect to GitHub. `anonymous` mode is enabled if `token` is not configured.
-	Token pulumi.StringPtrInput
 }
 
 func (ProviderArgs) ElementType() reflect.Type {

```

Basically, don't put the token in the state file.

I was able to then use `GITHUB_TOKEN` successfully to make some changes, and I don't have the token in the state file after the changes.

Obviously lacking context as to whether this reasoning here is correct and whether it would break things elsewhere. From what I could see, the token wasn't being referenced anywhere else in the SDK.

**Comment by nicktrav** [comment]
Thanks @stack72! ❤️

**Comment by stack72** [comment]
Hi @nicktrav 

Apologies it took so long but finally we got there - v3.0.1 is currently being released - give it 30 mins and it will be available as a plugin
